# Generated by Django 5.1 on 2024-08-24 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoaFisica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='')),
                ('em_estoque', models.BooleanField(default=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoaFisica.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoaFisica.funcionario')),
            ],
        ),
    ]
